// 20190815115558
// https://api.eluniversal.com.mx/v3/notes/eluniversal/mxm/json/home/portada


// Generated by https://quicktype.io

class PortadaResult {
  int           indexRanking;
  String        site;
  String        sitioDominio;
  int           id;
  String        idSeccion;
  String        idSubseccion;
  String        mainSection;
  String        section;
  dynamic       rankingPortada;
  String        title;
  String        subtitle;
  String        summary;
  String        author;
  String        pubdate;
  String        pubtime;
  int           timestamp;
  String        place;
  String        thumbnail;
  String        image;
  String        imageSmallSize;
  String        caption;
  String        audio;
  dynamic       gallery;
  String        video;
  int           rank;
  String        link;
  String        linkTitle;
  int           comments;
  int           premium;
  String        bodyHtml;
  String        body;
  String        seccionNombreApi;
  List<dynamic> embedNodes;
  List<dynamic> embedKaltura;
  dynamic       videoDataEmbed;
  dynamic       videoEmbed;
  dynamic       videoUrlApiCall;
  bool          optaWidget;
  dynamic       optaWidgetEmbed;
  dynamic       bodyOpta;
  String        iframeBodyHtml;
  String        rankingHome;
  String        tags;

  PortadaResult({
    this.indexRanking,
    this.site,
    this.sitioDominio,
    this.id,
    this.idSeccion,
    this.idSubseccion,
    this.mainSection,
    this.section,
    this.rankingPortada,
    this.title,
    this.subtitle,
    this.summary,
    this.author,
    this.pubdate,
    this.pubtime,
    this.timestamp,
    this.place,
    this.thumbnail,
    this.image,
    this.imageSmallSize,
    this.caption,
    this.audio,
    this.gallery,
    this.video,
    this.rank,
    this.link,
    this.linkTitle,
    this.comments,
    this.premium,
    this.bodyHtml,
    this.body,
    this.seccionNombreApi,
    this.embedNodes,
    this.embedKaltura,
    this.videoDataEmbed,
    this.videoEmbed,
    this.videoUrlApiCall,
    this.optaWidget,
    this.optaWidgetEmbed,
    this.bodyOpta,
    this.iframeBodyHtml,
    this.rankingHome,
    this.tags,
  });

  PortadaResult.fromJsonMap(Map<String, dynamic> json){

    indexRanking      = json['index_ranking'];
    site              = json['site'];
    sitioDominio      = json['sitio_dominio'];
    id                = json['id'];
    idSeccion         = json['id_seccion'];
    idSubseccion      = json['id_subseccion'];
    mainSection       = json['main_section'];
    section           = json['section'];
    rankingPortada    = json['ranking_portada'];
    title             = json['title'];
    subtitle          = json['subtitle'];
    summary           = json['summary'];
    author            = json['author'];
    pubdate           = json['pubdate'];
    pubtime           = json['pubtime'];
    timestamp         = json['timestamp'];
    place             = json['place'];
    thumbnail         = json['thumbnail'];
    image             = json['image'];
    imageSmallSize    = json['image_small_size'];
    caption           = json['caption'];
    audio             = json['audio'];
    gallery           = json['gallery'];
    video             = json['video'];
    rank              = json['rank'];
    link              = json['link'];
    linkTitle         = json['link_title'];
    comments          = json['comments'];
    premium           = json['premium'];
    bodyHtml          = json['body_html'];
    body              = json['body'];
    seccionNombreApi  = json['seccion_nombre_api'];
    embedNodes        = json['embed_nodes'];
    embedKaltura      = json['embed_kaltura'];
    videoDataEmbed    = json['video_data_embed'];
    videoEmbed        = json['video_embed'];
    videoUrlApiCall   = json['video_url_api_call'];
    optaWidget        = json['opta-widget'];
    optaWidgetEmbed   = json['opta-widget-embed'];
    bodyOpta          = json['body_opta'];
    iframeBodyHtml    = json['iframe_body_html'];
    rankingHome       = json['ranking_home'];
    tags              = json['tags'];


  }


getImg(){
  if( image == null ) { 
      return 'https://cdn.samsung.com/etc/designs/smg/global/imgs/support/cont/NO_IMG_600x600.png'; 
    } else {

      return 'https://image.tmdb.org/t/p/w500/$image';

    }

}
  

}


class PortadaResults{

  List<PortadaResult> items = new List();

  PortadaResults();

  PortadaResults.fromJsonList(List<dynamic> jsonList){

    if( jsonList == null ) return;

    for( var item in jsonList ){

      final portadaResult = new PortadaResult.fromJsonMap(item);
      items.add( portadaResult );

    }


  }

    
}

